name: Build & Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
#    paths-ignore:
#      - 'docs/**'
  pull_request:
    branches:
      - main

jobs:
  build-main:
    name: Build main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: bahmutov/npm-install@v1
        env:
          NODE_ENV: production
      - name: Build
        run: yarn build:main

  build-module:
    name: Build module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: bahmutov/npm-install@v1
        env:
          NODE_ENV: production
      - name: Build
        run: yarn build:module

  test-eslint:
    name: Test ESLint
    needs:
      - build-main
      - build-module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
      - name: Run ESLint
        run: yarn test:lint

  test-prettier:
    name: Test Prettier
    needs:
      - build-main
      - build-module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
      - name: Run Prettier
        run: yarn test:prettier

  test-chrome:
    name: Test Cypress (chrome)
    needs: [test-eslint, test-prettier]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome

  test-firefox:
    name: Test Cypress (firefox)
    needs: [test-eslint, test-prettier]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          browser: firefox

  test-edge:
    name: Test Cypress (edge)
    needs: [test-eslint, test-prettier]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          browser: edge
